import LayoutButtons from "@/components/Buttons/LayoutButtons";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-slate-900 text-white md:container md:mx-auto p-4 relative"
        }
      >
        <LayoutButtons/>
        {children}
      </body>
    </html>
  );
}
